// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: create_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRegulationRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegulationName string `protobuf:"bytes,1,opt,name=RegulationName,proto3" json:"RegulationName,omitempty"`
	Abbreviation   string `protobuf:"bytes,2,opt,name=Abbreviation,proto3" json:"Abbreviation,omitempty"`
	Title          string `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
}

func (x *CreateRegulationRequestMessage) Reset() {
	*x = CreateRegulationRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRegulationRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRegulationRequestMessage) ProtoMessage() {}

func (x *CreateRegulationRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_create_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRegulationRequestMessage.ProtoReflect.Descriptor instead.
func (*CreateRegulationRequestMessage) Descriptor() ([]byte, []int) {
	return file_create_message_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRegulationRequestMessage) GetRegulationName() string {
	if x != nil {
		return x.RegulationName
	}
	return ""
}

func (x *CreateRegulationRequestMessage) GetAbbreviation() string {
	if x != nil {
		return x.Abbreviation
	}
	return ""
}

func (x *CreateRegulationRequestMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateRegulationResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *CreateRegulationResponseMessage) Reset() {
	*x = CreateRegulationResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRegulationResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRegulationResponseMessage) ProtoMessage() {}

func (x *CreateRegulationResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_create_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRegulationResponseMessage.ProtoReflect.Descriptor instead.
func (*CreateRegulationResponseMessage) Descriptor() ([]byte, []int) {
	return file_create_message_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRegulationResponseMessage) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type CreateChapterRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChapterID    uint64 `protobuf:"varint,1,opt,name=ChapterID,proto3" json:"ChapterID,omitempty"`
	RegulationID uint64 `protobuf:"varint,2,opt,name=RegulationID,proto3" json:"RegulationID,omitempty"`
	ChapterName  string `protobuf:"bytes,3,opt,name=ChapterName,proto3" json:"ChapterName,omitempty"`
	ChapterNum   string `protobuf:"bytes,4,opt,name=ChapterNum,proto3" json:"ChapterNum,omitempty"`
	OrderNum     uint64 `protobuf:"varint,5,opt,name=OrderNum,proto3" json:"OrderNum,omitempty"`
}

func (x *CreateChapterRequestMessage) Reset() {
	*x = CreateChapterRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChapterRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChapterRequestMessage) ProtoMessage() {}

func (x *CreateChapterRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_create_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChapterRequestMessage.ProtoReflect.Descriptor instead.
func (*CreateChapterRequestMessage) Descriptor() ([]byte, []int) {
	return file_create_message_proto_rawDescGZIP(), []int{2}
}

func (x *CreateChapterRequestMessage) GetChapterID() uint64 {
	if x != nil {
		return x.ChapterID
	}
	return 0
}

func (x *CreateChapterRequestMessage) GetRegulationID() uint64 {
	if x != nil {
		return x.RegulationID
	}
	return 0
}

func (x *CreateChapterRequestMessage) GetChapterName() string {
	if x != nil {
		return x.ChapterName
	}
	return ""
}

func (x *CreateChapterRequestMessage) GetChapterNum() string {
	if x != nil {
		return x.ChapterNum
	}
	return ""
}

func (x *CreateChapterRequestMessage) GetOrderNum() uint64 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

type CreateChapterResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *CreateChapterResponseMessage) Reset() {
	*x = CreateChapterResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChapterResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChapterResponseMessage) ProtoMessage() {}

func (x *CreateChapterResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_create_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChapterResponseMessage.ProtoReflect.Descriptor instead.
func (*CreateChapterResponseMessage) Descriptor() ([]byte, []int) {
	return file_create_message_proto_rawDescGZIP(), []int{3}
}

func (x *CreateChapterResponseMessage) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type CreateParagraphsRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paragraphs []*Paragraph `protobuf:"bytes,1,rep,name=Paragraphs,proto3" json:"Paragraphs,omitempty"`
}

func (x *CreateParagraphsRequestMessage) Reset() {
	*x = CreateParagraphsRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateParagraphsRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateParagraphsRequestMessage) ProtoMessage() {}

func (x *CreateParagraphsRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_create_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateParagraphsRequestMessage.ProtoReflect.Descriptor instead.
func (*CreateParagraphsRequestMessage) Descriptor() ([]byte, []int) {
	return file_create_message_proto_rawDescGZIP(), []int{4}
}

func (x *CreateParagraphsRequestMessage) GetParagraphs() []*Paragraph {
	if x != nil {
		return x.Paragraphs
	}
	return nil
}

type CreateParagraphsResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *CreateParagraphsResponseMessage) Reset() {
	*x = CreateParagraphsResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateParagraphsResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateParagraphsResponseMessage) ProtoMessage() {}

func (x *CreateParagraphsResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_create_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateParagraphsResponseMessage.ProtoReflect.Descriptor instead.
func (*CreateParagraphsResponseMessage) Descriptor() ([]byte, []int) {
	return file_create_message_proto_rawDescGZIP(), []int{5}
}

func (x *CreateParagraphsResponseMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type FixLinksRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *FixLinksRequestMessage) Reset() {
	*x = FixLinksRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FixLinksRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixLinksRequestMessage) ProtoMessage() {}

func (x *FixLinksRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_create_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixLinksRequestMessage.ProtoReflect.Descriptor instead.
func (*FixLinksRequestMessage) Descriptor() ([]byte, []int) {
	return file_create_message_proto_rawDescGZIP(), []int{6}
}

func (x *FixLinksRequestMessage) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

var File_create_message_proto protoreflect.FileDescriptor

var file_create_message_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x82, 0x01, 0x0a, 0x1e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x67, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26,
	0x0a, 0x0e, 0x52, 0x65, 0x67, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x52, 0x65, 0x67, 0x75, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x62, 0x62, 0x72, 0x65, 0x76,
	0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x41, 0x62,
	0x62, 0x72, 0x65, 0x76, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x22, 0x31, 0x0a, 0x1f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x67, 0x75, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x49, 0x44, 0x22, 0xbd, 0x01, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68,
	0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x52, 0x65, 0x67, 0x75, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x68, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x70, 0x74,
	0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x68, 0x61,
	0x70, 0x74, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x4e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x4e, 0x75, 0x6d, 0x22, 0x2e, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61,
	0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x22, 0x4c, 0x0a, 0x1e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72,
	0x61, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x61, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x61, 0x72, 0x61,
	0x67, 0x72, 0x61, 0x70, 0x68, 0x52, 0x0a, 0x50, 0x61, 0x72, 0x61, 0x67, 0x72, 0x61, 0x70, 0x68,
	0x73, 0x22, 0x39, 0x0a, 0x1f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x28, 0x0a, 0x16,
	0x46, 0x69, 0x78, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_create_message_proto_rawDescOnce sync.Once
	file_create_message_proto_rawDescData = file_create_message_proto_rawDesc
)

func file_create_message_proto_rawDescGZIP() []byte {
	file_create_message_proto_rawDescOnce.Do(func() {
		file_create_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_create_message_proto_rawDescData)
	})
	return file_create_message_proto_rawDescData
}

var file_create_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_create_message_proto_goTypes = []interface{}{
	(*CreateRegulationRequestMessage)(nil),  // 0: CreateRegulationRequestMessage
	(*CreateRegulationResponseMessage)(nil), // 1: CreateRegulationResponseMessage
	(*CreateChapterRequestMessage)(nil),     // 2: CreateChapterRequestMessage
	(*CreateChapterResponseMessage)(nil),    // 3: CreateChapterResponseMessage
	(*CreateParagraphsRequestMessage)(nil),  // 4: CreateParagraphsRequestMessage
	(*CreateParagraphsResponseMessage)(nil), // 5: CreateParagraphsResponseMessage
	(*FixLinksRequestMessage)(nil),          // 6: FixLinksRequestMessage
	(*Paragraph)(nil),                       // 7: Paragraph
}
var file_create_message_proto_depIdxs = []int32{
	7, // 0: CreateParagraphsRequestMessage.Paragraphs:type_name -> Paragraph
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_create_message_proto_init() }
func file_create_message_proto_init() {
	if File_create_message_proto != nil {
		return
	}
	file_message_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_create_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRegulationRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRegulationResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChapterRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChapterResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateParagraphsRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateParagraphsResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FixLinksRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_create_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_create_message_proto_goTypes,
		DependencyIndexes: file_create_message_proto_depIdxs,
		MessageInfos:      file_create_message_proto_msgTypes,
	}.Build()
	File_create_message_proto = out.File
	file_create_message_proto_rawDesc = nil
	file_create_message_proto_goTypes = nil
	file_create_message_proto_depIdxs = nil
}
