// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: get_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDocumentRootRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetDocumentRootRequestMessage) Reset() {
	*x = GetDocumentRootRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDocumentRootRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRootRequestMessage) ProtoMessage() {}

func (x *GetDocumentRootRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_get_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRootRequestMessage.ProtoReflect.Descriptor instead.
func (*GetDocumentRootRequestMessage) Descriptor() ([]byte, []int) {
	return file_get_message_proto_rawDescGZIP(), []int{0}
}

func (x *GetDocumentRootRequestMessage) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type GetDocumentRootChapter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Num  string `protobuf:"bytes,2,opt,name=Num,proto3" json:"Num,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *GetDocumentRootChapter) Reset() {
	*x = GetDocumentRootChapter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDocumentRootChapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRootChapter) ProtoMessage() {}

func (x *GetDocumentRootChapter) ProtoReflect() protoreflect.Message {
	mi := &file_get_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRootChapter.ProtoReflect.Descriptor instead.
func (*GetDocumentRootChapter) Descriptor() ([]byte, []int) {
	return file_get_message_proto_rawDescGZIP(), []int{1}
}

func (x *GetDocumentRootChapter) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GetDocumentRootChapter) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

func (x *GetDocumentRootChapter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDocumentRootResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string                    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Title    string                    `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Chapters []*GetDocumentRootChapter `protobuf:"bytes,3,rep,name=Chapters,proto3" json:"Chapters,omitempty"`
}

func (x *GetDocumentRootResponseMessage) Reset() {
	*x = GetDocumentRootResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDocumentRootResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRootResponseMessage) ProtoMessage() {}

func (x *GetDocumentRootResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_get_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRootResponseMessage.ProtoReflect.Descriptor instead.
func (*GetDocumentRootResponseMessage) Descriptor() ([]byte, []int) {
	return file_get_message_proto_rawDescGZIP(), []int{2}
}

func (x *GetDocumentRootResponseMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDocumentRootResponseMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetDocumentRootResponseMessage) GetChapters() []*GetDocumentRootChapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

type GetAllDocumentsRegulation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *GetAllDocumentsRegulation) Reset() {
	*x = GetAllDocumentsRegulation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllDocumentsRegulation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDocumentsRegulation) ProtoMessage() {}

func (x *GetAllDocumentsRegulation) ProtoReflect() protoreflect.Message {
	mi := &file_get_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDocumentsRegulation.ProtoReflect.Descriptor instead.
func (*GetAllDocumentsRegulation) Descriptor() ([]byte, []int) {
	return file_get_message_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllDocumentsRegulation) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GetAllDocumentsRegulation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAllDocumentsResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Regulations []*GetAllDocumentsRegulation `protobuf:"bytes,1,rep,name=Regulations,proto3" json:"Regulations,omitempty"`
}

func (x *GetAllDocumentsResponseMessage) Reset() {
	*x = GetAllDocumentsResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllDocumentsResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDocumentsResponseMessage) ProtoMessage() {}

func (x *GetAllDocumentsResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_get_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDocumentsResponseMessage.ProtoReflect.Descriptor instead.
func (*GetAllDocumentsResponseMessage) Descriptor() ([]byte, []int) {
	return file_get_message_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllDocumentsResponseMessage) GetRegulations() []*GetAllDocumentsRegulation {
	if x != nil {
		return x.Regulations
	}
	return nil
}

type GetFullDocumentRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetFullDocumentRequestMessage) Reset() {
	*x = GetFullDocumentRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFullDocumentRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullDocumentRequestMessage) ProtoMessage() {}

func (x *GetFullDocumentRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_get_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullDocumentRequestMessage.ProtoReflect.Descriptor instead.
func (*GetFullDocumentRequestMessage) Descriptor() ([]byte, []int) {
	return file_get_message_proto_rawDescGZIP(), []int{5}
}

func (x *GetFullDocumentRequestMessage) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type GetFullDocumentResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string     `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Abbreviation string     `protobuf:"bytes,2,opt,name=Abbreviation,proto3" json:"Abbreviation,omitempty"`
	Title        string     `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Chapters     []*Chapter `protobuf:"bytes,4,rep,name=Chapters,proto3" json:"Chapters,omitempty"`
}

func (x *GetFullDocumentResponseMessage) Reset() {
	*x = GetFullDocumentResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFullDocumentResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullDocumentResponseMessage) ProtoMessage() {}

func (x *GetFullDocumentResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_get_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullDocumentResponseMessage.ProtoReflect.Descriptor instead.
func (*GetFullDocumentResponseMessage) Descriptor() ([]byte, []int) {
	return file_get_message_proto_rawDescGZIP(), []int{6}
}

func (x *GetFullDocumentResponseMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetFullDocumentResponseMessage) GetAbbreviation() string {
	if x != nil {
		return x.Abbreviation
	}
	return ""
}

func (x *GetFullDocumentResponseMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetFullDocumentResponseMessage) GetChapters() []*Chapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

type GetChapterRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetChapterRequestMessage) Reset() {
	*x = GetChapterRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChapterRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChapterRequestMessage) ProtoMessage() {}

func (x *GetChapterRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_get_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChapterRequestMessage.ProtoReflect.Descriptor instead.
func (*GetChapterRequestMessage) Descriptor() ([]byte, []int) {
	return file_get_message_proto_rawDescGZIP(), []int{7}
}

func (x *GetChapterRequestMessage) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type GetChapterResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chapter *Chapter `protobuf:"bytes,1,opt,name=chapter,proto3" json:"chapter,omitempty"`
}

func (x *GetChapterResponseMessage) Reset() {
	*x = GetChapterResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChapterResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChapterResponseMessage) ProtoMessage() {}

func (x *GetChapterResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_get_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChapterResponseMessage.ProtoReflect.Descriptor instead.
func (*GetChapterResponseMessage) Descriptor() ([]byte, []int) {
	return file_get_message_proto_rawDescGZIP(), []int{8}
}

func (x *GetChapterResponseMessage) GetChapter() *Chapter {
	if x != nil {
		return x.Chapter
	}
	return nil
}

var File_get_message_proto protoreflect.FileDescriptor

var file_get_message_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x65, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x44,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x6f, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x22, 0x4e, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x6f, 0x6f, 0x74, 0x43, 0x68, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x7f, 0x0a, 0x1e, 0x47, 0x65, 0x74,
	0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x6f, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x6f, 0x6f, 0x74, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72,
	0x52, 0x08, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x73, 0x22, 0x3f, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x67,
	0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x5e, 0x0a, 0x1e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3c, 0x0a,
	0x0b, 0x52, 0x65, 0x67, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x67, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b,
	0x52, 0x65, 0x67, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x2f, 0x0a, 0x1d, 0x47,
	0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x22, 0x94, 0x01, 0x0a,
	0x1e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x62, 0x62, 0x72, 0x65, 0x76, 0x69, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x41, 0x62, 0x62, 0x72, 0x65,
	0x76, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x24, 0x0a,
	0x08, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x08, 0x43, 0x68, 0x61, 0x70, 0x74,
	0x65, 0x72, 0x73, 0x22, 0x2a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x22,
	0x3f, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x07,
	0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x07, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_get_message_proto_rawDescOnce sync.Once
	file_get_message_proto_rawDescData = file_get_message_proto_rawDesc
)

func file_get_message_proto_rawDescGZIP() []byte {
	file_get_message_proto_rawDescOnce.Do(func() {
		file_get_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_get_message_proto_rawDescData)
	})
	return file_get_message_proto_rawDescData
}

var file_get_message_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_get_message_proto_goTypes = []interface{}{
	(*GetDocumentRootRequestMessage)(nil),  // 0: GetDocumentRootRequestMessage
	(*GetDocumentRootChapter)(nil),         // 1: GetDocumentRootChapter
	(*GetDocumentRootResponseMessage)(nil), // 2: GetDocumentRootResponseMessage
	(*GetAllDocumentsRegulation)(nil),      // 3: GetAllDocumentsRegulation
	(*GetAllDocumentsResponseMessage)(nil), // 4: GetAllDocumentsResponseMessage
	(*GetFullDocumentRequestMessage)(nil),  // 5: GetFullDocumentRequestMessage
	(*GetFullDocumentResponseMessage)(nil), // 6: GetFullDocumentResponseMessage
	(*GetChapterRequestMessage)(nil),       // 7: GetChapterRequestMessage
	(*GetChapterResponseMessage)(nil),      // 8: GetChapterResponseMessage
	(*Chapter)(nil),                        // 9: Chapter
}
var file_get_message_proto_depIdxs = []int32{
	1, // 0: GetDocumentRootResponseMessage.Chapters:type_name -> GetDocumentRootChapter
	3, // 1: GetAllDocumentsResponseMessage.Regulations:type_name -> GetAllDocumentsRegulation
	9, // 2: GetFullDocumentResponseMessage.Chapters:type_name -> Chapter
	9, // 3: GetChapterResponseMessage.chapter:type_name -> Chapter
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_get_message_proto_init() }
func file_get_message_proto_init() {
	if File_get_message_proto != nil {
		return
	}
	file_message_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_get_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDocumentRootRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_get_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDocumentRootChapter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_get_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDocumentRootResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_get_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllDocumentsRegulation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_get_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllDocumentsResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_get_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFullDocumentRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_get_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFullDocumentResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_get_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChapterRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_get_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChapterResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_get_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_get_message_proto_goTypes,
		DependencyIndexes: file_get_message_proto_depIdxs,
		MessageInfos:      file_get_message_proto_msgTypes,
	}.Build()
	File_get_message_proto = out.File
	file_get_message_proto_rawDesc = nil
	file_get_message_proto_goTypes = nil
	file_get_message_proto_depIdxs = nil
}
