// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: search_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchQuery string `protobuf:"bytes,1,opt,name=SearchQuery,proto3" json:"SearchQuery,omitempty"`
	Limit       string `protobuf:"bytes,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset      string `protobuf:"bytes,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
}

func (x *SearchRequestMessage) Reset() {
	*x = SearchRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequestMessage) ProtoMessage() {}

func (x *SearchRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_search_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequestMessage.ProtoReflect.Descriptor instead.
func (*SearchRequestMessage) Descriptor() ([]byte, []int) {
	return file_search_message_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequestMessage) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *SearchRequestMessage) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

func (x *SearchRequestMessage) GetOffset() string {
	if x != nil {
		return x.Offset
	}
	return ""
}

type SearchResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RID       string `protobuf:"bytes,1,opt,name=RID,proto3" json:"RID,omitempty"`
	RName     string `protobuf:"bytes,2,opt,name=RName,proto3" json:"RName,omitempty"`
	CID       string `protobuf:"bytes,3,opt,name=CID,proto3" json:"CID,omitempty"`
	CName     string `protobuf:"bytes,4,opt,name=CName,proto3" json:"CName,omitempty"`
	UpdatedAt string `protobuf:"bytes,5,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	PID       string `protobuf:"bytes,6,opt,name=PID,proto3" json:"PID,omitempty"`
	Text      string `protobuf:"bytes,7,opt,name=Text,proto3" json:"Text,omitempty"`
	Count     string `protobuf:"bytes,8,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *SearchResponseMessage) Reset() {
	*x = SearchResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponseMessage) ProtoMessage() {}

func (x *SearchResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_search_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponseMessage.ProtoReflect.Descriptor instead.
func (*SearchResponseMessage) Descriptor() ([]byte, []int) {
	return file_search_message_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponseMessage) GetRID() string {
	if x != nil {
		return x.RID
	}
	return ""
}

func (x *SearchResponseMessage) GetRName() string {
	if x != nil {
		return x.RName
	}
	return ""
}

func (x *SearchResponseMessage) GetCID() string {
	if x != nil {
		return x.CID
	}
	return ""
}

func (x *SearchResponseMessage) GetCName() string {
	if x != nil {
		return x.CName
	}
	return ""
}

func (x *SearchResponseMessage) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *SearchResponseMessage) GetPID() string {
	if x != nil {
		return x.PID
	}
	return ""
}

func (x *SearchResponseMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SearchResponseMessage) GetCount() string {
	if x != nil {
		return x.Count
	}
	return ""
}

var File_search_message_proto protoreflect.FileDescriptor

var file_search_message_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a, 0x14, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x51, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0xc1,
	0x01, 0x0a, 0x15, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x52, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x52, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x43, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x43,
	0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x43, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x49, 0x44, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x50, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_search_message_proto_rawDescOnce sync.Once
	file_search_message_proto_rawDescData = file_search_message_proto_rawDesc
)

func file_search_message_proto_rawDescGZIP() []byte {
	file_search_message_proto_rawDescOnce.Do(func() {
		file_search_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_search_message_proto_rawDescData)
	})
	return file_search_message_proto_rawDescData
}

var file_search_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_search_message_proto_goTypes = []interface{}{
	(*SearchRequestMessage)(nil),  // 0: SearchRequestMessage
	(*SearchResponseMessage)(nil), // 1: SearchResponseMessage
}
var file_search_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_search_message_proto_init() }
func file_search_message_proto_init() {
	if File_search_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_search_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_search_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_search_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_search_message_proto_goTypes,
		DependencyIndexes: file_search_message_proto_depIdxs,
		MessageInfos:      file_search_message_proto_msgTypes,
	}.Build()
	File_search_message_proto = out.File
	file_search_message_proto_rawDesc = nil
	file_search_message_proto_goTypes = nil
	file_search_message_proto_depIdxs = nil
}
