// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: service.proto

package pb

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RegulationGRPCClient is the client API for RegulationGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegulationGRPCClient interface {
	CreateRegulation(ctx context.Context, in *CreateRegulationRequestMessage, opts ...grpc.CallOption) (*CreateRegulationResponseMessage, error)
	CreateChapter(ctx context.Context, in *CreateChapterRequestMessage, opts ...grpc.CallOption) (*CreateChapterResponseMessage, error)
	CreateParagraphs(ctx context.Context, in *CreateParagraphsRequestMessage, opts ...grpc.CallOption) (*CreateParagraphsResponseMessage, error)
	FixLinks(ctx context.Context, in *FixLinksRequestMessage, opts ...grpc.CallOption) (*empty.Empty, error)
	GetDocumentRoot(ctx context.Context, in *GetDocumentRootRequestMessage, opts ...grpc.CallOption) (*GetDocumentRootResponseMessage, error)
	GetAllDocuments(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetAllDocumentsResponseMessage, error)
	GetFullDocument(ctx context.Context, in *GetFullDocumentRequestMessage, opts ...grpc.CallOption) (*GetFullDocumentResponseMessage, error)
	GetChapter(ctx context.Context, in *GetChapterRequestMessage, opts ...grpc.CallOption) (*GetChapterResponseMessage, error)
	Search(ctx context.Context, in *SearchRequestMessage, opts ...grpc.CallOption) (*SearchResponseMessage, error)
	SearchRegulations(ctx context.Context, in *SearchRequestMessage, opts ...grpc.CallOption) (*SearchResponseMessage, error)
	SearchChapters(ctx context.Context, in *SearchRequestMessage, opts ...grpc.CallOption) (*SearchResponseMessage, error)
	SearchPargaraphs(ctx context.Context, in *SearchRequestMessage, opts ...grpc.CallOption) (*SearchResponseMessage, error)
}

type regulationGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewRegulationGRPCClient(cc grpc.ClientConnInterface) RegulationGRPCClient {
	return &regulationGRPCClient{cc}
}

func (c *regulationGRPCClient) CreateRegulation(ctx context.Context, in *CreateRegulationRequestMessage, opts ...grpc.CallOption) (*CreateRegulationResponseMessage, error) {
	out := new(CreateRegulationResponseMessage)
	err := c.cc.Invoke(ctx, "/RegulationGRPC/CreateRegulation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regulationGRPCClient) CreateChapter(ctx context.Context, in *CreateChapterRequestMessage, opts ...grpc.CallOption) (*CreateChapterResponseMessage, error) {
	out := new(CreateChapterResponseMessage)
	err := c.cc.Invoke(ctx, "/RegulationGRPC/CreateChapter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regulationGRPCClient) CreateParagraphs(ctx context.Context, in *CreateParagraphsRequestMessage, opts ...grpc.CallOption) (*CreateParagraphsResponseMessage, error) {
	out := new(CreateParagraphsResponseMessage)
	err := c.cc.Invoke(ctx, "/RegulationGRPC/CreateParagraphs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regulationGRPCClient) FixLinks(ctx context.Context, in *FixLinksRequestMessage, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/RegulationGRPC/FixLinks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regulationGRPCClient) GetDocumentRoot(ctx context.Context, in *GetDocumentRootRequestMessage, opts ...grpc.CallOption) (*GetDocumentRootResponseMessage, error) {
	out := new(GetDocumentRootResponseMessage)
	err := c.cc.Invoke(ctx, "/RegulationGRPC/GetDocumentRoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regulationGRPCClient) GetAllDocuments(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetAllDocumentsResponseMessage, error) {
	out := new(GetAllDocumentsResponseMessage)
	err := c.cc.Invoke(ctx, "/RegulationGRPC/GetAllDocuments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regulationGRPCClient) GetFullDocument(ctx context.Context, in *GetFullDocumentRequestMessage, opts ...grpc.CallOption) (*GetFullDocumentResponseMessage, error) {
	out := new(GetFullDocumentResponseMessage)
	err := c.cc.Invoke(ctx, "/RegulationGRPC/GetFullDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regulationGRPCClient) GetChapter(ctx context.Context, in *GetChapterRequestMessage, opts ...grpc.CallOption) (*GetChapterResponseMessage, error) {
	out := new(GetChapterResponseMessage)
	err := c.cc.Invoke(ctx, "/RegulationGRPC/GetChapter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regulationGRPCClient) Search(ctx context.Context, in *SearchRequestMessage, opts ...grpc.CallOption) (*SearchResponseMessage, error) {
	out := new(SearchResponseMessage)
	err := c.cc.Invoke(ctx, "/RegulationGRPC/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regulationGRPCClient) SearchRegulations(ctx context.Context, in *SearchRequestMessage, opts ...grpc.CallOption) (*SearchResponseMessage, error) {
	out := new(SearchResponseMessage)
	err := c.cc.Invoke(ctx, "/RegulationGRPC/SearchRegulations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regulationGRPCClient) SearchChapters(ctx context.Context, in *SearchRequestMessage, opts ...grpc.CallOption) (*SearchResponseMessage, error) {
	out := new(SearchResponseMessage)
	err := c.cc.Invoke(ctx, "/RegulationGRPC/SearchChapters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regulationGRPCClient) SearchPargaraphs(ctx context.Context, in *SearchRequestMessage, opts ...grpc.CallOption) (*SearchResponseMessage, error) {
	out := new(SearchResponseMessage)
	err := c.cc.Invoke(ctx, "/RegulationGRPC/SearchPargaraphs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegulationGRPCServer is the server API for RegulationGRPC service.
// All implementations must embed UnimplementedRegulationGRPCServer
// for forward compatibility
type RegulationGRPCServer interface {
	CreateRegulation(context.Context, *CreateRegulationRequestMessage) (*CreateRegulationResponseMessage, error)
	CreateChapter(context.Context, *CreateChapterRequestMessage) (*CreateChapterResponseMessage, error)
	CreateParagraphs(context.Context, *CreateParagraphsRequestMessage) (*CreateParagraphsResponseMessage, error)
	FixLinks(context.Context, *FixLinksRequestMessage) (*empty.Empty, error)
	GetDocumentRoot(context.Context, *GetDocumentRootRequestMessage) (*GetDocumentRootResponseMessage, error)
	GetAllDocuments(context.Context, *empty.Empty) (*GetAllDocumentsResponseMessage, error)
	GetFullDocument(context.Context, *GetFullDocumentRequestMessage) (*GetFullDocumentResponseMessage, error)
	GetChapter(context.Context, *GetChapterRequestMessage) (*GetChapterResponseMessage, error)
	Search(context.Context, *SearchRequestMessage) (*SearchResponseMessage, error)
	SearchRegulations(context.Context, *SearchRequestMessage) (*SearchResponseMessage, error)
	SearchChapters(context.Context, *SearchRequestMessage) (*SearchResponseMessage, error)
	SearchPargaraphs(context.Context, *SearchRequestMessage) (*SearchResponseMessage, error)
	mustEmbedUnimplementedRegulationGRPCServer()
}

// UnimplementedRegulationGRPCServer must be embedded to have forward compatible implementations.
type UnimplementedRegulationGRPCServer struct {
}

func (UnimplementedRegulationGRPCServer) CreateRegulation(context.Context, *CreateRegulationRequestMessage) (*CreateRegulationResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRegulation not implemented")
}
func (UnimplementedRegulationGRPCServer) CreateChapter(context.Context, *CreateChapterRequestMessage) (*CreateChapterResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChapter not implemented")
}
func (UnimplementedRegulationGRPCServer) CreateParagraphs(context.Context, *CreateParagraphsRequestMessage) (*CreateParagraphsResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateParagraphs not implemented")
}
func (UnimplementedRegulationGRPCServer) FixLinks(context.Context, *FixLinksRequestMessage) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FixLinks not implemented")
}
func (UnimplementedRegulationGRPCServer) GetDocumentRoot(context.Context, *GetDocumentRootRequestMessage) (*GetDocumentRootResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocumentRoot not implemented")
}
func (UnimplementedRegulationGRPCServer) GetAllDocuments(context.Context, *empty.Empty) (*GetAllDocumentsResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllDocuments not implemented")
}
func (UnimplementedRegulationGRPCServer) GetFullDocument(context.Context, *GetFullDocumentRequestMessage) (*GetFullDocumentResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFullDocument not implemented")
}
func (UnimplementedRegulationGRPCServer) GetChapter(context.Context, *GetChapterRequestMessage) (*GetChapterResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChapter not implemented")
}
func (UnimplementedRegulationGRPCServer) Search(context.Context, *SearchRequestMessage) (*SearchResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedRegulationGRPCServer) SearchRegulations(context.Context, *SearchRequestMessage) (*SearchResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchRegulations not implemented")
}
func (UnimplementedRegulationGRPCServer) SearchChapters(context.Context, *SearchRequestMessage) (*SearchResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchChapters not implemented")
}
func (UnimplementedRegulationGRPCServer) SearchPargaraphs(context.Context, *SearchRequestMessage) (*SearchResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchPargaraphs not implemented")
}
func (UnimplementedRegulationGRPCServer) mustEmbedUnimplementedRegulationGRPCServer() {}

// UnsafeRegulationGRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegulationGRPCServer will
// result in compilation errors.
type UnsafeRegulationGRPCServer interface {
	mustEmbedUnimplementedRegulationGRPCServer()
}

func RegisterRegulationGRPCServer(s grpc.ServiceRegistrar, srv RegulationGRPCServer) {
	s.RegisterService(&RegulationGRPC_ServiceDesc, srv)
}

func _RegulationGRPC_CreateRegulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRegulationRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegulationGRPCServer).CreateRegulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RegulationGRPC/CreateRegulation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegulationGRPCServer).CreateRegulation(ctx, req.(*CreateRegulationRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegulationGRPC_CreateChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChapterRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegulationGRPCServer).CreateChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RegulationGRPC/CreateChapter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegulationGRPCServer).CreateChapter(ctx, req.(*CreateChapterRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegulationGRPC_CreateParagraphs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateParagraphsRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegulationGRPCServer).CreateParagraphs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RegulationGRPC/CreateParagraphs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegulationGRPCServer).CreateParagraphs(ctx, req.(*CreateParagraphsRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegulationGRPC_FixLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FixLinksRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegulationGRPCServer).FixLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RegulationGRPC/FixLinks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegulationGRPCServer).FixLinks(ctx, req.(*FixLinksRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegulationGRPC_GetDocumentRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRootRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegulationGRPCServer).GetDocumentRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RegulationGRPC/GetDocumentRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegulationGRPCServer).GetDocumentRoot(ctx, req.(*GetDocumentRootRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegulationGRPC_GetAllDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegulationGRPCServer).GetAllDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RegulationGRPC/GetAllDocuments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegulationGRPCServer).GetAllDocuments(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegulationGRPC_GetFullDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFullDocumentRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegulationGRPCServer).GetFullDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RegulationGRPC/GetFullDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegulationGRPCServer).GetFullDocument(ctx, req.(*GetFullDocumentRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegulationGRPC_GetChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChapterRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegulationGRPCServer).GetChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RegulationGRPC/GetChapter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegulationGRPCServer).GetChapter(ctx, req.(*GetChapterRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegulationGRPC_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegulationGRPCServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RegulationGRPC/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegulationGRPCServer).Search(ctx, req.(*SearchRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegulationGRPC_SearchRegulations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegulationGRPCServer).SearchRegulations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RegulationGRPC/SearchRegulations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegulationGRPCServer).SearchRegulations(ctx, req.(*SearchRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegulationGRPC_SearchChapters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegulationGRPCServer).SearchChapters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RegulationGRPC/SearchChapters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegulationGRPCServer).SearchChapters(ctx, req.(*SearchRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegulationGRPC_SearchPargaraphs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegulationGRPCServer).SearchPargaraphs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RegulationGRPC/SearchPargaraphs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegulationGRPCServer).SearchPargaraphs(ctx, req.(*SearchRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// RegulationGRPC_ServiceDesc is the grpc.ServiceDesc for RegulationGRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegulationGRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RegulationGRPC",
	HandlerType: (*RegulationGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRegulation",
			Handler:    _RegulationGRPC_CreateRegulation_Handler,
		},
		{
			MethodName: "CreateChapter",
			Handler:    _RegulationGRPC_CreateChapter_Handler,
		},
		{
			MethodName: "CreateParagraphs",
			Handler:    _RegulationGRPC_CreateParagraphs_Handler,
		},
		{
			MethodName: "FixLinks",
			Handler:    _RegulationGRPC_FixLinks_Handler,
		},
		{
			MethodName: "GetDocumentRoot",
			Handler:    _RegulationGRPC_GetDocumentRoot_Handler,
		},
		{
			MethodName: "GetAllDocuments",
			Handler:    _RegulationGRPC_GetAllDocuments_Handler,
		},
		{
			MethodName: "GetFullDocument",
			Handler:    _RegulationGRPC_GetFullDocument_Handler,
		},
		{
			MethodName: "GetChapter",
			Handler:    _RegulationGRPC_GetChapter_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _RegulationGRPC_Search_Handler,
		},
		{
			MethodName: "SearchRegulations",
			Handler:    _RegulationGRPC_SearchRegulations_Handler,
		},
		{
			MethodName: "SearchChapters",
			Handler:    _RegulationGRPC_SearchChapters_Handler,
		},
		{
			MethodName: "SearchPargaraphs",
			Handler:    _RegulationGRPC_SearchPargaraphs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
