---
app:
  id: read-only
  name: Read Only Service
  log-level: trace

grpc:
  ip: 0.0.0.0
  port: 30000

postgresql:
  host: 0.0.0.0
  port: "5432"
  username: postgres
  password: postgres
  database: prodservice
